!
! Copyright (C) 2001 PWSCF group
! This file is distributed under the terms of the
! GNU General Public License. See the file `License'
! in the root directory of the present distribution,
! or http://www.gnu.org/copyleft/gpl.txt .
!
!
!----------------------------------------------------------------------
!SUBROUTINE flipper_setlocal(aux_rho_of_g, flipper_energy_external)
SUBROUTINE flipper_setlocal()
  !----------------------------------------------------------------------
  !
  !    This routine computes the local potential in real space vltot(ir)
  !
  USE kinds,     ONLY : DP
  USE constants, ONLY : eps8
  USE ions_base, ONLY : zv, ntyp => nsp
  USE cell_base, ONLY : omega
  USE extfield,  ONLY : tefield, dipfield, etotefield
  USE gvect,     ONLY : igtongl, gg
  USE scf,       ONLY : rho, v_of_0, vltot
  USE vlocal,    ONLY : strf, vloc
  USE fft_base,  ONLY : dfftp
  USE fft_interfaces,ONLY : invfft
  USE gvect,     ONLY : nl, nlm, ngm, gstart
  USE control_flags, ONLY : gamma_only
  USE mp_bands,  ONLY : intra_bgrp_comm
  USE mp,        ONLY : mp_sum
  USE martyna_tuckerman, ONLY : wg_corr_loc, do_comp_mt
  USE esm,       ONLY : esm_local, esm_bc, do_comp_esm
  USE qmmm,      ONLY : qmmm_add_mm_field
  USE pinball
  !
  
  
  IMPLICIT NONE
  
!  COMPLEX(DP), intent(in) :: aux_rho_of_g (dfftp%nnr)
!~   REAL(DP), intent(in) :: aux_rho_of_r (dfftp%nnr)
  COMPLEX(DP), ALLOCATABLE :: vltot_g (:)
!~   , v_corr(:) 
!~   , vltot_g_to_get_vltot_r (:), vltot_r (:)
!  REAL(DP), intent(out) :: flipper_energy_external
!~   REAL(DP) :: flipper_cmplx
!~   REAL(DP) :: flipper_energy_external_copy
  ! auxiliary variable
  INTEGER :: nt, ng, igrid,igm
  ! counter on atom types
  ! counter on g vectors
  !
!~   ALLOCATE (vltot_r( dfftp%nnr))
  
  ALLOCATE (vltot_g( ngm))
!~   ALLOCATE (vltot_g_to_get_vltot_r( dfftp%nnr))
  
  vltot_g(:)=(0.d0,0.d0)
!~   vltot_r(:)=(0.d0,0.d0)
!~   vltot_g_to_get_vltot_r(:)=(0.d0,0.d0)

  DO nt = 1, ntyp
      DO ng = 1, ngm
          vltot_g (ng)                    = vltot_g(ng) + vloc (igtongl (ng), nt) * strf (ng, nt)
             ! Useful to get the real part of the VLTOT
             ! vltot_g_to_get_vltot_r (nl(ng)) = vltot_g_to_get_vltot_r(nl(ng)) + vloc (igtongl (ng), nt) * strf (ng, nt)
      END DO
  END DO
  
  
!~   IF (gamma_only) THEN
!~       DO ng = 1, ngm
!~           vltot_g_to_get_vltot_r (nlm(ng)) = CONJG(vltot_g_to_get_vltot_r (nl(ng)))
!~       END DO
!~   END IF
 !
  
  flipper_energy_external = 0.d0
  IF (gamma_only) THEN
      DO igm = gstart, ngm
        flipper_energy_external = flipper_energy_external &
                 + 2.d0 * DBLE(charge_g(igm))*DBLE(vltot_g(igm)) &
                 + 2.d0 * DIMAG(charge_g(igm))*DIMAG(vltot_g(igm)) 
      END DO
      if (gstart==2) flipper_energy_external = flipper_energy_external + charge_g(1)*conjg(vltot_g(1))
  ELSE
      DO igm = 1, ngm !aris
          flipper_energy_external = flipper_energy_external &
                 + DBLE(charge_g(igm)*CONJG(vltot_g(igm)))
      END DO
  END IF    
  
  flipper_energy_external = flipper_energy_external * omega
  
  call mp_sum(flipper_energy_external,intra_bgrp_comm)
  
  
!~   print*, 'flipper_energy_external', flipper_energy_external
!~    flipper_energy_external_copy = flipper_energy_external
  
  !
!~   CALL mp_sum( v_of_0, intra_bgrp_comm )
  !
  ! ... aux = potential in G-space . FFT to real space
  !
  
  
  
!~   CALL invfft ('Dense', vltot_g_to_get_vltot_r, dfftp)
  !
!~   vltot_r (:) =  DBLE (vltot_g_to_get_vltot_r (:) )
  
  
!~   flipper_energy_external = 0.d0
!~   DO igrid = 1, dfftp%nnr
!~     flipper_energy_external = flipper_energy_external &
!~              + vltot_r(igrid)*aux_rho_of_r(igrid) 
             
!~   END DO
!~   flipper_energy_external = flipper_energy_external * omega /(dfftp%nr1*dfftp%nr2*dfftp%nr3)
!~   call mp_sum(flipper_energy_external,intra_bgrp_comm)

!~   print*, 'FLIPPER ENERGY EXTERNAL', flipper_energy_external, flipper_cmplx
  
  
  
  !
  ! ... If required add an electric field to the local potential 
  !
!~   IF ( tefield .AND. ( .NOT. dipfield ) )  &
!~       CALL add_efield(vltot,etotefield,rho%of_r,.TRUE.)
  !
  !  ... Add the electrostatic field generated by MM atoms
  !  in a QM/MM calculation to the local potential
  !
!~   CALL qmmm_add_mm_field()
  !
  ! ... Save vltot for possible modifications in plugins
  !
!~   CALL plugin_init_potential()
  !
  DEALLOCATE(vltot_g)
!~   DEALLOCATE(vltot_r)
!~   DEALLOCATE(vltot_g_to_get_vltot_r)
  !
!~   RETURN
END SUBROUTINE flipper_setlocal

